### ISSUE TITLE
Favicon will not load due to content security policy

### ISSUE THREAD

**Issue by themagicpanda** [nadrad/s4notes#1]
Hi,

Not a programmer, but something I noticed the favicon (or any image for this purpose) will not load due to the content security policy set in the script.

I have adjusted the script to include an img-src allowed type in the CSP, not sure if this potentially lessens security, but I wanted to add a logo to it, on top of the favicon not working.

The new CSP would be
	header
	(
		"Content-Security-Policy: "
		."default-src 'none'; "
		**."img-src 'self';"**
		."style-src 'unsafe-inline'; "
		."block-all-mixed-content "
	);

Let me know your thoughts on whether you think this is a potential risk.

**Comment by nadrad** [comment]
Thanks; I didn't even notice that the favicon doesn't show up!

I'm not an expert, but I think allowing self-origin images is safe enough. I just added it to the code.
